/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import entidades.Persona;
import archivo.*;
import javax.swing.JOptionPane;
/**
 *
 * @author vr
 */
public class FrmIngresoPersona extends javax.swing.JFrame {

    /**
     * Creates new form FrmIngresoPersona
     */
    public FrmIngresoPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCedula = new javax.swing.JLabel();
        lNombres = new javax.swing.JLabel();
        lApellidos = new javax.swing.JLabel();
        lEdad = new javax.swing.JLabel();
        tfCedula = new javax.swing.JTextField();
        tfNombres = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfEdad = new javax.swing.JTextField();
        bIngresar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lCedula.setText("Cédula:");

        lNombres.setText("Nombres:");

        lApellidos.setText("Apellidos:");

        lEdad.setText("Edad:");

        bIngresar.setText("INGRESAR");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        bLimpiar.setText("LIMPIAR");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(bLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lEdad)
                            .addComponent(lApellidos)
                            .addComponent(lNombres)
                            .addComponent(lCedula))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCedula)
                            .addComponent(tfNombres)
                            .addComponent(tfApellidos)
                            .addComponent(tfEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCedula)
                    .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombres)
                    .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lApellidos)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEdad)
                    .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIngresar)
                    .addComponent(bLimpiar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void limpiarFormulario(){
        tfCedula.setText("");
        tfNombres.setText(null);
        tfApellidos.setText(null);
        tfEdad.setText(null);    
    }
    
    private boolean formularioValido(){
        if(tfCedula.getText().equals("") ||
           tfNombres.getText().equals("") ||
           tfApellidos.getText().equals("") ||
           tfEdad.getText().equals("")){
            JOptionPane.showMessageDialog(null,
             "Formulario incompleto",
             "Ingreso",JOptionPane.ERROR_MESSAGE);
            return false;
        }
    
        try{
            Integer.parseInt(tfEdad.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,
             "Debe ingrese un número en la edad",
             "Ingreso",JOptionPane.ERROR_MESSAGE);
            return false;
        }    
    
        
        return true;
    }
    
    
    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        // TODO add your handling code here:
        if(formularioValido()){
            String cedula       = tfCedula.getText();
            String nombres      = tfNombres.getText();
            String apellidos    = tfApellidos.getText();
            int edad            = Integer.parseInt(tfEdad.getText());
            Persona p           = new Persona(cedula, nombres, apellidos, edad);
            if(Archivo.insertar_registro(p)){
                JOptionPane.showMessageDialog(null,
                 "Se ingresó correctamente el registro",
                 "Ingreso",JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();                
            }else{
                JOptionPane.showMessageDialog(null,
                 "Ocurrió un error en el ingreso",
                 "Ingreso",JOptionPane.ERROR_MESSAGE);
            }
        }    
    }//GEN-LAST:event_bIngresarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JLabel lApellidos;
    private javax.swing.JLabel lCedula;
    private javax.swing.JLabel lEdad;
    private javax.swing.JLabel lNombres;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfCedula;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfNombres;
    // End of variables declaration//GEN-END:variables
}
