/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

/**
 *
 * @author CISCO
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mInicio = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        mMantenimiento = new javax.swing.JMenu();
        mPersona = new javax.swing.JMenu();
        jEditar = new javax.swing.JMenuItem();
        jIngresar = new javax.swing.JMenuItem();
        jEliminar = new javax.swing.JMenuItem();
        mSensor = new javax.swing.JMenu();
        jEditarS = new javax.swing.JMenuItem();
        jIngresarS = new javax.swing.JMenuItem();
        jEliminarS = new javax.swing.JMenuItem();
        mAcercaDe = new javax.swing.JMenu();
        mIntegrantes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mInicio.setText("Inicio");

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mInicio.add(mSalir);

        jMenuBar1.add(mInicio);

        mMantenimiento.setText("Mantenimiento");

        mPersona.setText("Personas");

        jEditar.setText("Editar");
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });
        mPersona.add(jEditar);

        jIngresar.setText("Ingresar");
        jIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarActionPerformed(evt);
            }
        });
        mPersona.add(jIngresar);

        jEliminar.setText("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });
        mPersona.add(jEliminar);

        mMantenimiento.add(mPersona);

        mSensor.setText("Sensores");

        jEditarS.setText("Editar");
        mSensor.add(jEditarS);

        jIngresarS.setText("Ingresar");
        mSensor.add(jIngresarS);

        jEliminarS.setText("Eliminar");
        mSensor.add(jEliminarS);

        mMantenimiento.add(mSensor);

        jMenuBar1.add(mMantenimiento);

        mAcercaDe.setText("Acerca De");

        mIntegrantes.setText("Integrantes");
        mAcercaDe.add(mIntegrantes);

        jMenuBar1.add(mAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
        System.out.println("Salir");
        System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
        frmPersona perso = new frmPersona();
        perso.setVisible(true);
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed
        // TODO add your handling code here:
        frmPersona perso = new frmPersona();
        perso.setVisible(true);
    }//GEN-LAST:event_jEditarActionPerformed

    private void jIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarActionPerformed
        // TODO add your handling code here:
        FrmIngresarPersona ing = new FrmIngresarPersona();
        ing.setVisible(true);
    }//GEN-LAST:event_jIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jEditar;
    private javax.swing.JMenuItem jEditarS;
    private javax.swing.JMenuItem jEliminar;
    private javax.swing.JMenuItem jEliminarS;
    private javax.swing.JMenuItem jIngresar;
    private javax.swing.JMenuItem jIngresarS;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAcercaDe;
    private javax.swing.JMenu mInicio;
    private javax.swing.JMenuItem mIntegrantes;
    private javax.swing.JMenu mMantenimiento;
    private javax.swing.JMenu mPersona;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenu mSensor;
    // End of variables declaration//GEN-END:variables
}
